### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by brianloyal** [ntranoslab/esm-variants#1]
Just read your publication in Nature - Great work. Can you please add a LICENSE file to this repository so others know how to give you proper attribution?

**Comment by timbitz** [comment]
+1 on this issue.  I agree, very interesting paper, and some useful functions here that would be nice to utilize without having to re-implement from scratch (eg. calculating LLR on ESM models).  @vasilisNt, my understanding is that no license implies no rights for usage (https://choosealicense.com/no-permission/).  Are there plans to add a permissive license here?

**Comment by nadavbra** [comment]
@timbitz @brianloyal Apologies for the late response. We just added an MIT license.
