### ISSUE TITLE
Incorportion of ESM3 models

### ISSUE THREAD

**Issue by jacekzkominek** [ntranoslab/esm-variants#10]
Since the ESM3 model came out recently (https://github.com/evolutionaryscale/esm) I wanted to ask if it's possible to incorporate the new model onto the variant scoring somehow? Is it even possible, and if so - would it improve on anything in this context or not really?

Now, I realize that the group now operates as an independent company and all that, so it's a different situation than back when they were part of FAIR at Meta, but I wanted to ask out of curiosity nonetheless.

**Comment by nadavbra** [comment]
Hi @jacekzkominek,
We haven't really looked at ESM3 yet, but it definitely sounds like a promising thing to try. I expect that, at least in principle, it would be relatively easy to plug ESM3 into our framework. We have the code and benchmarks publicly available, so it should be straightforward to evaluate ESM3 and see how it compares to the ESM1 models if you want to try it.
One complication though is that ESM3 is no longer an open model (except of a smaller variation of the model that they did make open), so it would depend on what parts of the model are accessible through the API.
