### ISSUE TITLE
Use the esm_score_multi_residue_mutations.py to calculate missense mutation LLR score

### ISSUE THREAD

**Issue by JieHe233** [ntranoslab/esm-variants#2]
Can I use the script used for calculating PLLR(esm_score_multi_residue_mutations) to calculate the LLR score of the missense mutation?

**Comment by nadavbra** [comment]
@JieHe233 No, it will give you the PLLR of missense mutations, not the LLR. In theory PLLR is a valid score for missense mutations too, but we don't know how it compares in terms of performance (in our paper we only evaluated LLR scores in the case of missense mutations). I'd therefore recommend that you use the LLR scores for missense mutations, which can be obtained by the script `esm_score_missense_mutations`.

**Comment by JieHe233** [comment]
@nadavbra OK, I got it. Thanks for your reply.
