### ISSUE TITLE
Why can not open the web portal

### ISSUE THREAD

**Issue by towering979** [ntranoslab/esm-variants#3]
''We created a web portal allowing users to query, visualize and download missense VEPs for all human protein isoforms (accessible at https://huggingface.co/spaces/ntranoslab/esm_variants).''

I can't open the web

ERRORS
```
This site can’t be reachedhuggingface.co took too long to respond.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
[Running Windows Network Diagnostics](javascript:diagnoseErrors())
ERR_CONNECTION_TIMED_OUT
```

How to solve it?
thank you!

**Comment by nadavbra** [comment]
I'm able to access our portal.
Might it be an issue with your network?
Can you try to connect from another network?

**Comment by towering979** [comment]
It is running now.
I think it might be my network port problem.
Thank you.
