### ISSUE TITLE
Script to convert numerous variants (VCF) into amino acid sequences

### ISSUE THREAD

**Issue by wmeng1018** [ntranoslab/esm-variants#5]
Hi there, thank you for your impressive work!

I'd like to test your software/scripts on our own indel variant lists, but what I have are VCF files (with a large number of indels). Since the input for ESM variants are fasta files with protein/AA sequences, I'm wondering if you can provide existing scripts or recommended tools to translate/convert accordingly. Much appreciate it!

Meng

**Comment by nadavbra** [comment]
Hi @wmeng1018 

You can use the [Ensembl vep](https://useast.ensembl.org/info/docs/tools/vep/index.html) tool to annotate the protein sequence effects of your variants. I'd expect that vep or another Ensembl tool would allow you to fetch the relevant protein sequences association with these variant effects. You can try asking the Ensembl team what's the simplest way to retrieve them.

**Comment by wmeng1018** [comment]
> Hi @wmeng1018
> 
> You can use the [Ensembl vep](https://useast.ensembl.org/info/docs/tools/vep/index.html) tool to annotate the protein sequence effects of your variants. I'd expect that vep or another Ensembl tool would allow you to fetch the relevant protein sequences association with these variant effects. You can try asking the Ensembl team what's the simplest way to retrieve them.

Thank you for the quick reply. Actually, I already have the protein effect annotations for the variants, like p.Q166R. Just don't know how to get the entire protein sequences more efficiently. I saw you have done benchmark on ClinVar and HGMD data and assumed you might have the best tool. Anyway, I will do more research on that and try to contact the Ensembl team. Thanks again

**Comment by YBoulaimen** [comment]
Hello @wmeng1018 ,
I am also looking to convert vcf files to protein sequences.
Did you happen to find a solution or any recommended tools/scripts for this conversion?
Thank you in advance!

**Comment by wmeng1018** [comment]
> Hello @wmeng1018 , I am also looking to convert vcf files to protein sequences. Did you happen to find a solution or any recommended tools/scripts for this conversion? Thank you in advance!

Unfortunately, in our case for checking indels, we didn't get any good solution to convert, so we used metaRNN to predict instead. As I know, the newest version of dbNSFP includes EVE, AlphaMissense, and ESM1b annotations for SNVs if that's what you're looking for. You could use ANNOVAR to annotate accordingly. Hope this will help^-^
