### ISSUE TITLE
Query about datasets

### ISSUE THREAD

**Issue by ShugangZhang** [ntranoslab/esm-variants#7]
Hi team, thanks for your great work! I am currently using your model as baseline and trying to reproduce some results on benchmark datasets. However, I feel difficult to match the reported number of variants to that in the '/benchmark' folder. For example, in Supplementary Methods, it writes "we used 46,726 variants with high-qulity ClinVar labels (i.e., at least 1 'Gold Stars')". When I filtered your data in "ClinVar_gnomAD_benchmark_with_predictions.csv" by setting "Gold_stars" bigger than 0, I got only 42,440 entries. Could you kindly give more details about the dataset? Thanks for your help.

**Comment by nadavbra** [comment]
@ShugangZhang 
I apologize for the late response.
It looks like the discrepancy stems from file we uploaded (with 42,362 variants having `clinvar_label` and `Gold_stars >= 1`) including only the variants that were also included in the dbNSFP dataset, which is a subset of the full dataset with 46,726 variants. I'm sorry we didn't explain it clearly.
