### ISSUE TITLE
(Question/resource request) Structures for MEN1 Isoform1 and 2 from figure 5c

### ISSUE THREAD

**Issue by jyaacoub** [ntranoslab/esm-variants#8]
Hi, 
I am just trying to replicate some of your results and was wondering where I can get the AlphaFold structures referenced in Figure 5c. To be specific these are O00255-2 and O00255-1. The same ones from the figure would be great, if not at least the configuration for the prediction itself would be much appreciated.

<img width="601" alt="image" src="https://github.com/ntranoslab/esm-variants/assets/50300488/c90ec59f-c324-459d-9474-210764f0de6a">

Thanks!
Jean

**Comment by nadavbra** [comment]
@jyaacoub 
Sorry for the late response.
We used https://github.com/sokrypton/ColabFold for the structure predictions.
Here are the structures we used for the MEN1 isoforms: [structures.zip](https://github.com/ntranoslab/esm-variants/files/14089380/structures.zip)

**Comment by jyaacoub** [comment]
Thank you for this! very helpful.
